### ISSUE TITLE
Algorithm 

### ISSUE THREAD

**Issue by intcpd** [aEnigmatic/ffbe-jp#5]
Hey,

Do you know the new Algorithm for FFBE JP? i know it's aes cbc but no luck on the full algo

**Comment by aEnigmatic** [comment]
It's CBC with an IV (and PCKS5 padding)

**Comment by intcpd** [comment]
Thank you

I can't get it to work for whatever reason, it only decrypts 95% this is my set up in c#

   AesCryptoServiceProvider cryptoProvider = new AesCryptoServiceProvider();
                    cryptoProvider.Mode = CipherMode.CBC;
                    cryptoProvider.Padding = PaddingMode.PKCS7;
                    cryptoProvider.Key = keyBytes;
                    cryptoProvider.GenerateIV();
                    ICryptoTransform transform = cryptoProvider.CreateDecryptor();
                    CryptoStreamMode mode = CryptoStreamMode.Write;
