### ISSUE TITLE
Banners

### ISSUE THREAD

**Issue by intcpd** [aEnigmatic/ffbe-jp#6]
Are u able to pull more Data? a lots are missing, like Banners?

**Comment by aEnigmatic** [comment]
Banners (and probably most other stuff you're thinking of) are sent by the server and not recorded in the local game files.
In the case of banners, the stuff that is sent is mostly irrelevant anyway, just the banner image, dates, etc.

**Comment by intcpd** [comment]
Okay, Thank you

Question,

I can't get it to decrypt, only 95% this is my set up in c#

AesCryptoServiceProvider cryptoProvider = new AesCryptoServiceProvider();
cryptoProvider.Mode = CipherMode.CBC;
cryptoProvider.Padding = PaddingMode.PKCS7;
cryptoProvider.Key = keyBytes;
cryptoProvider.GenerateIV();
ICryptoTransform transform = cryptoProvider.CreateDecryptor();
CryptoStreamMode mode = CryptoStreamMode.Write;

Any idea or help? maybe discord works better, mine is envydrivesyou #8922
