### ISSUE TITLE
Data Mining a day early?

### ISSUE THREAD

**Issue by intcpd** [aEnigmatic/ffbe-jp#7]
Hey,

Your latest Files were a day before Maintenance happened, could you update? Also, my Question from before, it isn't working for me for some reason.

I can't get it to decrypt, only 95% this is my set up in c#

AesCryptoServiceProvider cryptoProvider = new AesCryptoServiceProvider();
cryptoProvider.Mode = CipherMode.CBC;
cryptoProvider.Padding = PaddingMode.PKCS7;
cryptoProvider.Key = keyBytes;
cryptoProvider.GenerateIV();
ICryptoTransform transform = cryptoProvider.CreateDecryptor();
CryptoStreamMode mode = CryptoStreamMode.Write;

Any idea or help? maybe discord works better, mine is envydrivesyou #8922

**Comment by aEnigmatic** [comment]
I sometimes forget about JP :D

The problem is that you need a specific IV, not generate a new one.

**Comment by intcpd** [comment]
Thank you

**Comment by intcpd** [comment]
as it happened, another maintenance... needs updating again

**Comment by intcpd** [comment]
5/15 17:00 JST
